package vista;

import conexion.conexion;
import controlador.Ctrl_Categoria;
import java.awt.Dimension;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JTable;
import java.awt.event.MouseAdapter;
import java.awt.Component;
import java.awt.event.MouseEvent;
import vista.InterGestionarCategorias;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import modelo.Categoria;
/**
 *
 * @author FERNANDO
 */
public class InterGestionarCategorias extends javax.swing.JInternalFrame {

  private int idCategoria;
    
    public InterGestionarCategorias() {
        initComponents();
        this.setSize(new Dimension(600,400));
        this.setTitle(" Gestionar Categorias ");
        this.CargarTablaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_categorias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adminstrar Categorias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_categorias);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 30));

        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 140, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Descripcion: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_descripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 190, 80));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
            if (!txt_descripcion.getText().isEmpty()) {
            Categoria categoria = new Categoria();
                Ctrl_Categoria contrCategoria = new Ctrl_Categoria();
                
                categoria.setDescripcion(txt_descripcion.getText());
                if (contrCategoria.actualizar(categoria, idCategoria)) {
                  JOptionPane.showMessageDialog(null, "Categoria Actualizada");
                  txt_descripcion.setText("");
                  this.CargarTablaCategoria();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al axtualizar la categoria");
                }
                
        } else {
                JOptionPane.showMessageDialog(null, "seleccione la categoria");
        }
        
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
              if (!txt_descripcion.getText().isEmpty()) {
            Categoria categoria = new Categoria();
                Ctrl_Categoria contrCategoria = new Ctrl_Categoria();
                
                categoria.setDescripcion(txt_descripcion.getText());
                if (!contrCategoria.eliminar(idCategoria)) {
                  JOptionPane.showMessageDialog(null, "Categoria Eliminada");
                  txt_descripcion.setText("");
                  this.CargarTablaCategoria();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al Eliminar la categoria");
                }
                
        } else {
                JOptionPane.showMessageDialog(null, "seleccione la categoria");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_categorias;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables

// metodo para mostrar todas las categorias registradas
private void CargarTablaCategoria(){
Connection con = conexion.conectar();
    DefaultTableModel model = new DefaultTableModel();
    String sql = "Select idCategoria, descripcion, estado from tb_categoria";
    Statement st;
    try {
       st = con.createStatement();
       ResultSet rs = st.executeQuery(sql);
       InterGestionarCategorias.jTable_categorias = new JTable(model);
       InterGestionarCategorias.jScrollPane1.setViewportView(InterGestionarCategorias.jTable_categorias);
       
       model.addColumn("idCategorias");
       model.addColumn("descripcion");
       model.addColumn("estado");
       
       while(rs.next()){
       Object fila[] = new Object[3];
       
       for(int i = 0; i < 3; i++) {
       fila[i] = rs.getObject( i + 1);
       }   
       model.addRow(fila);
       }
       con.close();
    } catch (SQLException e) {
        System.out.println("Error al rellenar la tabla: " + e);
    }
jTable_categorias.addMouseListener(new MouseAdapter(){

    @Override
    public void mouseClicked(MouseEvent e){
    int fila_point = jTable_categorias.rowAtPoint(e.getPoint());
    int columna_point = 0;
    
        if (fila_point >-1) {
            idCategoria = (int) model.getValueAt(fila_point, columna_point);
            EnviarDatosCategoriaSeleccionada(idCategoria);
        }
    }
});
}
    private void EnviarDatosCategoriaSeleccionada(int idCategoria){
    try {
        
        Connection con = conexion.conectar();
        PreparedStatement pst = con.prepareStatement("select * from tb_categoria where idCategoria = '"+ idCategoria+"'");
             ResultSet rs = pst.executeQuery();
             if (rs.next()) {
            txt_descripcion.setText(rs.getString("descripcion"));
        }
                con.close();
    } catch (SQLException e) {
        System.out.println("Error al cargar tabla categoria: " + e);
    }
}


}
