/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.JTextField;
import static vista.FrmMenu.jDesktopPane_menu;
/**
 *
 * @author FERNANDO
 */
public class InterGrafica extends javax.swing.JInternalFrame {

   public static String fecha_inicio = "", fecha_final = "";
    
    public InterGrafica() {
        initComponents();
        this. setSize(new Dimension (450,300));
        this.setTitle("Historial de Ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_graficar_ventas = new javax.swing.JButton();
        jDateChooser_fecha_inicial = new com.toedter.calendar.JDateChooser();
        jDateChooser_fecha_final = new com.toedter.calendar.JDateChooser();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione Fecha para Graficar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Inicial:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Final:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jButton_graficar_ventas.setText("Graficar Ventas");
        jButton_graficar_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficar_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_graficar_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jDateChooser_fecha_inicial.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fecha_inicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jDateChooser_fecha_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, -1));

        jDateChooser_fecha_final.setDateFormatString("yyyy-MM-dd\n");
        jDateChooser_fecha_final.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jDateChooser_fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_graficar_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficar_ventasActionPerformed
        fecha_inicio = ((JTextField)jDateChooser_fecha_inicial.getDateEditor().getUiComponent()).getText();
        fecha_final = ((JTextField)jDateChooser_fecha_final.getDateEditor().getUiComponent()).getText();
        
        InterGraficaVenta interGraficaVenta = new InterGraficaVenta();
        jDesktopPane_menu.add(interGraficaVenta);
        interGraficaVenta.setVisible(true);
        
    }//GEN-LAST:event_jButton_graficar_ventasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_graficar_ventas;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_final;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_inicial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
